name: avelia
description: Tu compañero de bienestar emocional con IA
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  intl: ^0.18.1
  flutter_local_notifications: ^14.1.4
  permission_handler: ^10.4.5
  sensors_plus: ^3.1.0
  health: ^8.0.0
  audioplayers: ^5.2.1
  flutter_markdown: ^0.6.18
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^4.0.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  in_app_purchase: ^3.1.11
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_messaging: ^14.7.9
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.7
  mockito: ^5.4.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700